In [20]:
#Tensorflow (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)

import tensorflow as tf
import numpy as np

#--Create
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

#--Read
print("Tensor is : \n",rank_3_tensor)
print("Tensor to array : \n",rank_3_tensor.numpy())
print("Tensor last element  : ",rank_3_tensor[2,1,4])
#--Update
reshaped = tf.reshape(rank_3_tensor, [5, 3, 2])
print("The reshaped tensor is : \n",reshaped)
#--Delete
del rank_3_tensor


Tensor is : 
 tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
Tensor to array : 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
Tensor last element  :  tf.Tensor(29, shape=(), dtype=int32)
The reshaped tensor is : 
 tf.Tensor(
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]], shape=(5, 3, 2), dtype=int32)
